### ISSUE TITLE
Broken pattern matching with guards

### ISSUE THREAD

**Issue by turlando** [purescm/purescm#63]
The following code, taken from [List](https://github.com/purescript/purescript-lists/blob/v6.0.1/src/Data/List.purs#L521-L521)

```
take :: forall a. Int -> List a -> List a
take = go Nil
  where
  go acc n _ | n < 1 = reverse acc
  go acc _ Nil = reverse acc
  go acc n (x : xs) = go (x : acc) (n - 1) xs
```

is translated to

```
(define take
  (letrec*
     ([go
       (lambda (acc)
         (lambda (v)
           (lambda (v1)
             (cond
              [#t (cond
                   [(fx<? v 1) (reverse acc)]
                   [else (error #f "Failed pattern match kvtleflvhe")])]
              [(eq? (car v1) (quote Nil)) (reverse acc)]
              [(eq? (car v1) (quote Cons))
               (((go ((Data.List.Types.Cons (vector-ref (cdr v1) 0)) acc)) (fx- v 1)) (vector-ref (cdr v1) 1))]
              [else (error #f "Failed pattern match wahyysksgx")]))))])
    (go Data.List.Types.Nil)))
```

and it always triggers the error for `kvtleflvhe`.

**Comment by f-f** [comment]
There are really two separate bugs here:
1. Whenever there's a `NullBinder` we emit `#t` for the whole branch, which is not correct because there might be other binders that we should bind to
2. We are emitting a nested `cond` for guards, which is not correct: if we don't match a branch with a guard we should just fall through to the next branch, but since we already committed to be inside the nested branch, if the guard fails we instead throw a "pattern match failed"
